# Site settings
name: Linwei DING
email: linweiding@smail.nju.edu.cn
url: 
description: "Graduate Student, School of Arts, Nanjing University. Email: linweiding@smail.nju.edu.cn"
author: "author"
title: "BlogFolio"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social

twitter:
  username: ding_linwei

linkedin:
  username: linwei-ding-6570b419b
