# Site settings
name: Linwei DING
email: linweiding@smail.nju.edu.cn
url: 
description: "Graduate Student, School of Arts, Nanjing University. Email: linweiding@smail.nju.edu.cn"
author: "Linwei DING"
title: "Linwei DING"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social

twitter:
  username: ding_linwei

